### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by baerbock** [powsybl/powsybl-geo-data#7]
Is powsybl-geo-data not yet ready or is there an issue my maven environment?
`[ERROR] Failed to execute goal on project powsybl-geo-data-server: Could not resolve dependencies for project com.powsybl:powsybl-geo-data-server:jar:1.0.0-SNAPSHOT: Could not find artifact com.powsybl:powsybl-network-store-client:jar:1.0.0-SNAPSHOT -> [Help 1]`

**Comment by mathbagu** [comment]
This project depends on powsybl-network-store-client 1.0.0-SNAPSHOT. As we don’t publish snapshot versions of our artifacts, you have to install it manually:
- clone powsybl-network-store-client
- run « mvn install » in it, to build and install the artefact in your local maven repository 
- run « mvn » again in this repository
